# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 521ada54e82bdee23c6a1f42a83cd22898f1efd4  # frozen: v1.99.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
